### PR TITLE
Fix highlighting of keyword `defined?` in Ruby

### LINKED ISSUE #1241: Ruby lexer does not detect `defined?` as a keyword for parenthesized argument
### **Name of the lexer**
ruby

### **Code sample**

```ruby
raise "Hellfire" unless defined?(Rouge)
state :peace do
  load 'rouge'
end
```

### **Screenshots**

Ruby Visual Test

### Additional context

Unlike other keywords which are usually flanked by whitespace, `defined?` is mostly used with parentheses.

### PR DESCRIPTION
**Pull request by ashmaroli**
Resolves #1241

### Before

image

### After

image

### CODE REVIEW

File: lib/rouge/lexers/ruby.rb [hunk 1]
```diff
@@ -183,7 +183,7 @@ def self.detect?(text)
 
         mixin :strings
 
-        rule %r/(?:#{keywords.join('|')})\b/, Keyword, :expr_start
+        rule %r/(?:#{keywords.join('|')})(?=[ ]*\b|\()/, Keyword, :expr_start
```
Comment (pyrmont) [inline lib/rouge/lexers/ruby.rb]: Do we want to match the word boundary if there are spaces? Won't that mean that strings that have non-word characters (eg. `[`) aren't matched if they come after spaces but are matched if they don't come after spaces?

Comment (ashmaroli) [reply lib/rouge/lexers/ruby.rb]: To be honest, this regex is a hack to work with Ruby lexer's `keywords` array.

The word boundary matches at the position between `\w` and `\W`. Ideally, we wouldn't need to match or test for whitespace if we're also testing for word boundary.
But in this case, our *keyword* is `/defined\?/`. Word boundary is either before the first `d` and after the last `d`. Therefore, `/defined\?\b/` would never match.

I'll define a new `rule` to eliminate this cognitive overhead.

Comment (pyrmont) [reply lib/rouge/lexers/ruby.rb]: Ahhhh, yeah, I get it now. I like the consistency of having `defined?` be included in `keywords` but it does simplify the (human) parsing of the rules to split it out. 

At the risk of making this an ideal example of bikeshedding, do you think it might be better to use the following rule:

```ruby
rule %r/(?:#{keywords.join('|')})(?=\W|$)/, Keyword, :expr_start
```

Comment (ashmaroli) [reply lib/rouge/lexers/ruby.rb]: *Au contraire*, your suggestion is the more apt change. :smiley:

Comment (pyrmont) [reply lib/rouge/lexers/ruby.rb]: It was your explanation :)
