### PR TITLE
Fix escape sequences in Python's raw strings

### LINKED ISSUE #1507: Python lexer broken for raw strings in v3.18.0
**Name of the lexer**
Python

**Code sample**

The two below examples show that escaped characters in raw strings confuse the lexer.

```python
import re
s = "Hello World"
m = re.findall(r"^[\w]+", s)
print(m)
```
([rouge.jneen.net](http://rouge.jneen.net/v3.18.0/python/aW1wb3J0IHJlCnMgPSAiSGVsbG8gV29ybGQiCm0gPSByZS5maW5kYWxsKHIiXltcd10rIiwgcykKcHJpbnQobSk))

```python
devid_line = status_line.split('STATUS:')[0]
result_line = status_line.split('STATUS:')[1]
print(f'Parsing "{result_line}"...')

# parse devid string
pattern = re.compile(r'.*\[p00t_(d\d{4})\].*')
data = pattern.match(devid_line)
devid = data.group(1)
```
([rouge.jneen.net](http://rouge.jneen.net/v3.18.0/python/ZGV2aWRfbGluZSA9IHN0YXR1c19saW5lLnNwbGl0KCdTVEFUVVM6JylbMF0KcmVzdWx0X2xpbmUgPSBzdGF0dXNfbGluZS5zcGxpdCgnU1RBVFVTOicpWzFdCnByaW50KGYnUGFyc2luZyAie3Jlc3VsdF9saW5lfSIuLi4nKQoKIyBwYXJzZSBkZXZpZCBzdHJpbmcKcGF0dGVybiA9IHJlLmNvbXBpbGUocicuKlxbcDAwdF8oZFxkezR9KVxdLionKQpkYXRhID0gcGF0dGVybi5tYXRjaChkZXZpZF9saW5lKQpkZXZpZCA9IGRhdGEuZ3JvdXAoMSk))

**Additional context**

There is an issue in the GitLab issue tracker which describes the same problem:
https://gitlab.com/gitlab-org/gitlab/-/issues/215643

I traced the problem back to commit 652a6227: Use generic string states in Python lexer (#1477)

### PR DESCRIPTION
**Pull request by pyrmont**
Version 3.18.0 of Rouge included a new mechanism for handling strings in the Python lexer. One of the consequences of that change was that raw strings would break if they included 'invalid' escape sequences. This is a mistake as raw strings do not have 'invalid' escape sequences.

This PR fixes that error by adding a special state for escape sequences with raw strings. A separate state is still necessary because `\` can be used in raw strings to prevent the particular string's delimiter from matching.

This fixes #1507.

### CODE REVIEW

**Comment by pyrmont** [comment]
@tuxu Sorry again about the regression. How does this look?

File: lib/rouge/lexers/python.rb [hunk 1]
```diff
@@ -215,14 +216,9 @@ def current_string
...
-          if current_string.type? "r"
-            token Str
-          else
-            token Str::Escape
-          end
-          pop!
-        end
+        )x, Str::Escape, :pop!
+
+        rule %r/./, Error, :pop!
```
Comment (pyrmont) [inline lib/rouge/lexers/python.rb:221]: @tuxu Should this be an error? I was looking at what happens if I write `"\p"` in the Python REPL and it looks like it comes back without any issues. Should `"\p"` just be highlighted as a plain string?

Comment (pyrmont) [reply lib/rouge/lexers/python.rb]: After thinking more about this, I think it's wrong to mark these as errors. Non-valid escape sequences should just be tokenised as regular strings, I think. The new commit does that.

**Comment by tueksta** [comment]
Looks great, let's get this merged :)

**Comment by pyrmont** [comment]
@tuxu @tueksta Thanks for your review. Version 3.19.0 of Rouge is scheduled for later tonight/early tomorrow (depending on your time zone). This will be part of that release 🎉
