### PR TITLE
Kotlin: Fix highlighting plugin names for build.gradle.kts files

### LINKED ISSUE #927: Kotlin Script Support
Syntax highlighting is missing for **kts** (Kotlin Script) files. Without highlighting it is difficult to read a kts file. One major use for kts files is with [Gradle build scripts](https://github.com/gradle/kotlin-dsl). More and more Kotlin projects use Gradle via the official Kotlin DSL, especially in server-side projects. Another major use for kts files is for [scripting JVM based tools](https://www.youtube.com/watch?v=cOJPKhlRa8c).

Most of the work required to do the highlighting is already done (about 95%), since the highlighting for **kt** (Kotlin source) files would cover just about everything.

## Other Links

- [Gradle Goes Kotlin](https://www.youtube.com/watch?v=4gmanjWNZ8E)
- [KotlinConf 2017 - Building Kotlin Applications at Scale with Gradle](https://www.youtube.com/watch?v=lg5hPBEIQ2E)
- [Writing Gradle Build Scripts in Kotlin - Gradle Summit 2016](https://www.youtube.com/watch?v=vv4zh_oPBTw)
- [The Kotlin DSL experience in Gradle](https://www.youtube.com/watch?v=m7tNOHUcDPU)

### LINKED ISSUE #1325: Hyphen support in Kotlin scripts
@napperly [wrote](https://github.com/rouge-ruby/rouge/issues/927#issuecomment-429742486):

> Kotlin Script files are now recognised, however highlighting doesn't work properly with words surrounded by back ticks. Can see a example of this here: https://gitlab.com/webscene/webscene-core/blob/master/js/build.gradle.kts#L8

The original issue as filed was for Kotlin script support. This issue is really about the use of hyphens [as noted](https://github.com/rouge-ruby/rouge/issues/927#issuecomment-529099030) by @lordcodes.

### PR DESCRIPTION
**Pull request by lordcodes**
When using Gradle Kotlin DSL, the contents are Kotlin code. However, in this situation you may have an identifier that contains a dash, due to it referring to the name of a Gradle plugin.

Without this change it doesn't match at all and if the plugin name is wrapped in back-ticks it marks those as errors.

E.g.
```
plugins {
  `maven-publish-plugin`
}
```

Fixes #927
Fixes #1325 

@pyrmont

### CODE REVIEW

File: lib/rouge/lexers/kotlin.rb [hunk 1]
```diff
@@ -29,6 +29,8 @@ class Kotlin < RegexLexer
 
       id = %r'(#{name_backtick})'
 
+      plugin_name = %r'@?[_\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Nl}][\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Nl}\p{Nd}\p{Pc}\p{Cf}\p{Mn}\p{Mc}\p-]*'
```
Comment (pyrmont) [inline lib/rouge/lexers/kotlin.rb]: Two issues with this:

1. It seems duplicative of `name`. Perhaps extract the content of the character class into a string and then create both regular expressions using interpolation?

2. In Ruby 2.6.3 I get an error in `irb` when making a regular expression with `\p-`. I think it should just be `-` (I'd also move it to the front of the class, ahead of `_` so that it doesn't create ambiguity as to whether it's a range).

In light of the discussion in #1325, it may make sense to wait until that's addressed before making further changes to this PR.

File: lib/rouge/lexers/kotlin.rb [hunk 2]
```diff
@@ -87,6 +89,7 @@ class Kotlin < RegexLexer
         rule %r"[0-9](\.[0-9]+)?([eE][+-][0-9]+)?[flFL]?|0[xX][0-9a-fA-F]+[Ll]?", Num
         rule %r/@#{id}/, Name::Decorator
         rule id, Name
+        rule %r'#{plugin_name}|`#{plugin_name}`', Name
```
Comment (pyrmont) [inline lib/rouge/lexers/kotlin.rb]: Depending on the approach taken to backticks, it may become unnecessary to include the alternate here.

**Comment by pyrmont** [comment]
@lordcodes Did anything change with the force-pushed code? It didn't appear that it did but am not sure.

**Comment by lordcodes** [comment]
Sorry, no just rebasing branches. I will comment when all these updates are
done!

**Comment by pyrmont** [comment]
@lordcodes No problem—understood!

File: lib/rouge/lexers/kotlin.rb (hunk 2 above)
Comment (lordcodes) [reply lib/rouge/lexers/kotlin.rb]: This rule wasn't needed anymore

File: lib/rouge/lexers/kotlin.rb (hunk 1 above)
Comment (lordcodes) [reply lib/rouge/lexers/kotlin.rb]: The \p was me still getting used to some of the Ruby notation.
In the end after making changes in the other PR to simplify the name regexes, this fix could be done just be allowing '-' as well as '_' in the name regex. This is valid, as users may have different naming conventions for their properties/functions etc.

For example, a common convention for test function names includes underscores.

**Comment by lordcodes** [comment]
Changes are rebased on top of changes for #1326 so this PR should wait until that PR is merged first, so I can update this after that merge.

**Comment by lordcodes** [comment]
@pyrmont This PR is rebased onto latest master and is ready to go again!

**Comment by pyrmont** [comment]
@lordcodes And so ends this series of improvements to the Kotlin lexer. Thank you again! :tada:

**Comment by lordcodes** [comment]
@pyrmont Haha, thanks for your help getting them merged! Its been fun! Will make the code snippets look much better on my blog too 🎉

**Comment by pyrmont** [comment]
Yep, definitely. The best part of maintaining the project is collaborating with other people to improve the code. It's kind of crazy when you stop and think about all the infrastructure that allows that to happen—yay Internet! :)

**Comment by lordcodes** [comment]
Couldn't agree more! 👍
