### PR TITLE
Kotlin: Simplify regexes and name fixes

### LINKED ISSUE #1324: Rationalise regular expressions in Kotlin lexer
**Name of the lexer**
Kotlin

**Code sample**
https://github.com/rouge-ruby/rouge/blob/7b876784f61444da6d3a9a8ada0a2ace8b13621a/lib/rouge/lexers/kotlin.rb#L27-L30

**Additional context**
Does `id` have any purpose? It's used throughout the lexer rather than `name` but as best as I can tell is just `name` inside a capture group. The capture group is never used, which seems wasteful.

Directing this at you, @lordcodes, because I'm not familiar with Kotlin and so am not sure if there would be a reason to have done things this particular way.

### PR DESCRIPTION
**Pull request by lordcodes**
Simplify the regex for matching names/identifiers in the Kotlin lexer.

Rather than having a regex for name with or without wrapped back-ticks, just have optional match for back-tick at start and end of the identifier.

Remove unnecessary id regex, when it just wrapped name into capture group.

Fix annotation matching, as it was surrounding the full name rule with @ and uppercase start. However, this meant it looked for back-ticks after the uppercase first character.

Locations that are matching for Name::Class token now look for class_name so expect capital first letter.

Remove @ from the name matcher, as there was already a separate rule to match annotations and marking them as Name::Decorator instead.

Fixes #1324

@pyrmont

### CODE REVIEW

File: lib/rouge/lexers/kotlin.rb [hunk 1]
```diff
@@ -73,50 +71,50 @@ class Kotlin < RegexLexer
...
+        rule %r'(#{class_name})(<)' do
           groups Name::Class, Punctuation
           push :generic_parameters
         end
-        rule %r'(#{upper}#{name_backtick})', Name::Class
-        rule %r'(#{name_backtick})(?=\s*[({])', Name::Function
-        rule id, Name
+        rule %r'(#{class_name})', Name::Class
+        rule %r'(#{name})(?=\s*[({])', Name::Function
+        rule %r'#{name}', Name
```
Comment (pyrmont) [inline lib/rouge/lexers/kotlin.rb]: I like the visual consistency of interpolating the regex but this creates objects. Can you replace it with `name`? Same with the other instances below.

Comment (lordcodes) [reply lib/rouge/lexers/kotlin.rb]: Ah yes of course, sorry slipped my mind that the properties were regexes themselves. Will do that now!

Comment (lordcodes) [reply lib/rouge/lexers/kotlin.rb]: Done 👍

**Comment by pyrmont** [comment]
@lordcodes Thanks for all your help on the Kotlin lexer recently! I think this is a great improvement on the clarity of the code :)

**Comment by lordcodes** [comment]
@pyrmont Thank you. Happy to help! Great to see it cleaned up and so much more being highlighted!
