### PR TITLE
Fix YAML key containing special characters

### LINKED ISSUE #778: YAML syntax highlighting for keys with periods and forward slashes
If you place a period in YAML key, the highlighting looks wrong. Are periods in keys not valid YAML or is there a problem with the syntax highlighting? I've tested this using the [online previewer](http://rouge.jneen.net/) with this YAML:
```
a: 1
b.c: 2
d: 3
```

### PR DESCRIPTION
**Pull request by tancnle**
The regex is lifted from the `YamlLexer` class in `Pygments` library (see [more](https://github.com/pygments/pygments/blob/debda34e2d4f28d6d369cdafdcba4791702f63fc/pygments/lexers/data.py#L235)).

| Before | After |
| -- | -- |
| Screen Shot 2021-01-20 at 9 47 46 pm | Screen Shot 2021-01-20 at 9 48 22 pm |

Closes #778

### CODE REVIEW

File: spec/lexers/digdag_spec.rb [hunk 1]
```diff
@@ -21,7 +21,7 @@
 
     it 'recognizes one line comment on last line even when not terminated by a new line (#360)' do
       assert_tokens_equal "+step1:\n  echo> Hello!\n",
-        ["Literal.String", "+step1"],
+        ["Name.Attribute", "+step1"],
```
Comment (dblessing) [inline spec/lexers/digdag_spec.rb:24]: This does change the way Digdag is highlighted. But I think after the change it's 'more correct' than originally. In Digdag ["+" is a task](https://docs.digdag.io/workflow_definition.html#is-a-task) but since this is delegated to YAML lexer, I think this is OK. If Digdag wanted this highlighted differently it should do that itself.

**Review by dblessing — APPROVED** [review]
Thanks @tancnle. I like the simplicity of this Regex opposed to the exist one.
